name: 🚀 Deploy website on push
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 📂 Sync files via FTPS (dry-run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}        # ex.: gatorXXXX.hostgator.com
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          timeout: 60000

          server-dir: public_html/pokedex-PxG/   # relativo ao root do FTP
          local-dir: ./                          # ou dist/ se tiver build

          dry-run: true
          log-level: verbose
          exclude: |
            **/.git/**
            **/.github/**
            **/.git*
            **/.vscode/**
            **/.idea/**
            **/node_modules/**
            **/.DS_Store
            **/README.md
            **/*.map
